default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  <<: *default
  database: todo_app_test
  username: root
  password:
  host: 127.0.0.1
production:
  <<: *default
  database: todo_app
  username: root
  password:
  socket: /tmp/mysql.sock
